name: rllab3-adv
channels:
    - https://conda.anaconda.org/kne 
    - https://conda.binstar.org/tlatorre 
    - https://conda.anaconda.org/cjs14
    - https://conda.anaconda.org/menpo
    - jjhelmus
dependencies:
    - python==3.5.2
    - numpy==1.10.4
    - scipy
    - path.py
    - python-dateutil
    - joblib==0.9.4
    - mako
    - ipywidgets
    - numba
    - flask
    - pybox2d
    - pygame
    - h5py
    - matplotlib
    - opencv3=3.1.0
    - scikit-learn
    - tensorflow=0.10.0rc0
    - pip:
        - Pillow
        - atari-py
        - pyprind
        - ipdb
        - boto3
        - PyOpenGL
        - nose2
        - pyzmq
        - msgpack-python
        - mujoco_py
        - cached_property
        - line_profiler
        - Cython
        - theano==0.8.0
        - lasagne==0.1
        - plotly==4.14.3
        - awscli
        - git+https://github.com/lerrel/gym-adv.git
        - pyglet
        - git+https://github.com/neocxi/prettytensor.git
        - jupyter
        - progressbar2
        - chainer==1.15.0
